#################################
## SCR4 Docker Container 
## nginx, php 7.2 (+ xdebug), php-fpm, mariadb 10.3 (and git for composer)
## base port 6969 (web), mariadb on 3306, xdebug on 9001 and adminer on 8080
## db root password: scr4
## default database: default
## default user: user
## default pwd: scr4
#################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.3
      container_name: scr4-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=scr4
        - MYSQL_DATABASE=default
        - MYSQL_USER=user
        - MYSQL_PASSWORD=scr4
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: scr4-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "6969:80"


    php-fpm:
      build: configs/php
      container_name: scr4-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./configs/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    adminer:
      image: adminer
      container_name: scr4-adminer
      working_dir: /application
      links:
        - mariadb:db
      ports:
        - 8080:8080
